Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"


  config.vm.provision "shell", inline: <<-SHELL
  sudo useradd adminuser                        
  echo adminuser | passwd adminuser --stdin     
  sudo usermod -aG wheel adminuser              
  sudo useradd poweruser                        
  echo poweruser | passwd poweruser --stdin     
  sudo usermod -aG wheel poweruser              
  setfacl -m g:poweruser:rx /home/adminuser     
  find / -perm /4000                            

  SHELL
end
