Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.network "forwarded_port", guest: 80, host: 8888

  config.vm.network "forwarded_port", guest: 80, host: 8888, host_ip: "127.0.0.1"


  config.vm.provision "shell", inline: <<-SHELL
  sudo find / -type l
   sed -n '/^Character/, /^$/ { /^$/ !p }' /proc/devices
   sed -n '/^Block/, /^$/ { /^$/ !p }' /proc/devices
   sudo ln -sf tmp/file  /etc/hostname
   sudo useradd testuser
   sudo  touch /home/testuser/testuser_data && sudo chown testuser:testuser /home/testuser/testuser_data
   SHELL
end
